GRANT USAGE ON SCHEMA public TO gsm_backend;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gsm_backend;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO gsm_backend;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO gsm_backend;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO gsm_backend;
